/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fjw.struts.action;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Timestamp;
import java.util.Date;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.fjw.domain.Art;
import com.fjw.domain.Cat;
import com.fjw.domain.FileContent;
import com.fjw.domain.Nav;
import com.fjw.service.ArtService;
import com.fjw.service.CatService;
import com.fjw.service.FileContentService;
import com.fjw.service.NavService;
import com.fjw.struts.form.AddForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2016
 * 
 * XDoclet definition:
 * @struts.action path="/add" name="addForm" scope="request"
 */
public class AddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddForm addForm = (AddForm) form;
		if(request.getSession().getAttribute("user")==null) {
			return mapping.findForward("goHome");
		}
		
		int navId=-1,catId=-1;
		try{
			navId=getParameterAsInt(request,"nav");
			catId=getParameterAsInt(request,"cat");
		} catch(Exception e) {
			;
		}
		if(navId==-1) {
			return mapping.findForward("goHome");
		}
		
		FileContent fileContent=null;
		if("".equals(addForm.getImageFile().getFileName())==false) {
			fileContent=FileContentService.createFileContent(addForm.getImageFile(), this);
			if(fileContent==null) {
				request.setAttribute("info", "上传图片失败");
				return mapping.findForward("result");
			}
		}
		
		if(catId!=-1) {
			Art art=new Art();
			art.setNavId(navId);
			art.setCatId(catId);
			art.setTitle(addForm.getTitle());
			art.setImage(fileContent);
			art.setContent(addForm.getContent());
			art.setTimestamp(new Timestamp(new Date().getTime()));
			art=ArtService.createArt(art);
			if(art==null) {
				request.setAttribute("info", "添加文章失败");
			} else {
				request.setAttribute("info", "添加文章成功");
			}
			return mapping.findForward("result");
		} else if(navId!=-1) {
			Cat cat=new Cat();
			cat.setNavId(navId);
			cat.setTitle(addForm.getTitle());
			cat.setImage(fileContent);
			cat.setContent(addForm.getContent());
			cat=CatService.createCat(cat);
			if(cat==null) {
				request.setAttribute("info", "添加栏目失败");
			} else {
				request.setAttribute("info", "添加栏目成功");
			}
			return mapping.findForward("result");
		}
		
		return mapping.findForward("result");
	}
	
	private int getParameterAsInt(HttpServletRequest request, String param) throws Exception {
		String str=request.getParameter(param);
		if(str==null) {
			throw new Exception();
		}
		int id=0;
		try {
			id=Integer.parseInt(str);
		} catch(NumberFormatException e) {
			throw new Exception();
		}
		if(id<=0) {
			throw new Exception();
		}
		return id;
	}
}