/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fjw.struts.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.fjw.util.ZipUtils;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2016
 * 
 * XDoclet definition:
 * @struts.action
 */
public class BackupFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(request.getSession().getAttribute("user")==null) {
			return mapping.findForward("goHome");
		}
		response.setContentType("text/html");
		try {
			response.setHeader("Content-Disposition", "attachment;filename="+
					java.net.URLEncoder.encode("网站文件备份-"+new SimpleDateFormat("yyyyMMddHHmmss").format(new Date())+".zip","UTF-8"));
		} catch (UnsupportedEncodingException e1) {
			request.setAttribute("info", "设置信息头失败");
			return null;
		}
		ZipUtils zip=new ZipUtils();
		try {
			zip.setOutputStream(response.getOutputStream());
		} catch (IOException e) {
			request.setAttribute("info", "初始化下载流失败");
			return null;
		}
		zip.setInputFile(this.getServlet().getServletContext().getRealPath("/file"));
		zip.generateFileList();
		try {
			zip.zipIt();
		} catch (IOException e) {
			request.setAttribute("info", "下载中断");
			return null;
		}
		request.setAttribute("info", "下载成功");
		return null;
	}
}