/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fjw.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.fjw.service.ArtService;
import com.fjw.service.CatService;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2016
 * 
 * XDoclet definition:
 * @struts.action
 */
public class DelAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(request.getSession().getAttribute("user")==null) {
			return mapping.findForward("goHome");
		}
		
		int navId=-1,catId=-1,artId=-1;
		try{
			navId=getParameterAsInt(request, "nav");
			catId=getParameterAsInt(request, "cat");
			artId=getParameterAsInt(request, "art");
		} catch(Exception e) {
			;
		}
		
		if(catId==-1) {
			return mapping.findForward("goHome");
		}
		if(artId!=-1) {
			if(ArtService.deleteArt(navId,catId,artId)==true) {
				request.setAttribute("info", "删除成功");
			} else {
				request.setAttribute("info", "删除失败");
			}
			return mapping.findForward("result");
		} else {
			if(CatService.deleteCat(navId,catId)==true) {
				request.setAttribute("info", "删除成功");
			} else {
				request.setAttribute("info", "删除失败");
			}
			return mapping.findForward("result");
		}
		
	}
	
	private int getParameterAsInt(HttpServletRequest request, String param) throws Exception {
		String str=request.getParameter(param);
		if(str==null) {
			throw new Exception();
		}
		int id=0;
		try {
			id=Integer.parseInt(str);
		} catch(NumberFormatException e) {
			throw new Exception();
		}
		if(id<=0) {
			throw new Exception();
		}
		return id;
	}
}