/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fjw.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2016
 * 
 * XDoclet definition:
 * @struts.form name="addForm"
 */
public class AddForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** content property */
	private String content;

	/** title property */
	private String title;

	/** imageFile property */
	private FormFile imageFile;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the content.
	 * @return String
	 */
	public String getContent() {
		return content;
	}

	/** 
	 * Set the content.
	 * @param content The content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the imageFile.
	 * @return FormFile
	 */
	public FormFile getImageFile() {
		return imageFile;
	}

	/** 
	 * Set the imageFile.
	 * @param imageFile The imageFile to set
	 */
	public void setImageFile(FormFile imageFile) {
		this.imageFile = imageFile;
	}
}